### PR TITLE
Add support for multiple files

### PR DESCRIPTION
**Pull request by ehedbor**

### CODE REVIEW

**Comment by ehedbor** [comment]
This branch was based off the prettier branch and was created before the PR (#23) was accepted. It seems that Git thinks the prettier commits in main are different from the ones in this branch, so its counting all the changes twice. Now Git is asking me to resolve changes that are supposed to be in the past and I'm not entirely sure how to fix this.

**Comment by PaddiM8** [comment]
I rebased it to change the parent commit. Seems to have worked.

**Comment by PaddiM8** [comment]
@AnHeuermann

**Comment by PaddiM8** [comment]
Yeah that was the problem indeed. It should now add documents that don't belong to a library in the workspace.

**Comment by PaddiM8** [comment]
Could you re-run the tests?

**Comment by AnHeuermann** [comment]
I forgot to enable the contributor license agreement for this repository. I enabled it just now, and it tells that everybody did sign the CLA. @ehedbor and @PaddiM8 can you confirm or is it just broken?

**Comment by AnHeuermann** [comment]
Did a quick double check and everybody signed the CLA. Perfect.

**Review by AnHeuermann — APPROVED** [review]

**Pull request merged**
